spring:
  application:
    name: testing

logging:
  level:
    root: INFO
#    com.yourpackage: DEBUG  # optional, for more detail
  file:
    name: logs/app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7