package com.achhecode.testing.entity;

import lombok.Data;
import lombok.NoArgsConstructor;
//import lombok.RequiredArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import java.time.Instant;
import java.time.LocalDate;

@Document(collection = "user_details")
@Data
@NoArgsConstructor
//@RequiredArgsConstructor
public class UserDetails {
    @Id
    private String id; // default generated by mongo

    private String username;
    private String name;
    @Field("date_of_birth")
    private LocalDate dateOfBirth;
    @Field("email")
    private String email;
    @Field("phone_no")
    private long phoneNo;
    private String address;

    public UserDetails(String username, String name, LocalDate dateOfBirth, String email, long phoneNo, String address){
        this.username = username;
        this.name = name;
        this.dateOfBirth = dateOfBirth;
        this.email = email;
        this.phoneNo = phoneNo;
        this.address = address;
    }

}
